spring:
  application:
    name: transfer-service

  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

    hikari:
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"

  endpoint:
    health:
      show-details: always